### ISSUE TITLE
Design DB

### ISSUE THREAD

**Issue by eatplaynap** [eatplaynap/shadone#7]
Design database and create ERD

**Comment by yoshitsugu** [comment]
確認しました！すいませんが前提がわかってないところがあり、一旦疑問点だけ確認させてください！

- Practicesは一日につき1レコードできるような想定でしょうか？
  - 一日に複数種類のURLを見ることもできますか？
  - その場合はそれぞれ詳細画面が表示できるようなイメージでしょうか？

**Comment by eatplaynap** [comment]
> Practicesは一日につき1レコードできるような想定でしょうか？

はい、その想定です〜！

> 一日に複数種類のURLを見ることもできますか？

1日につき、URLはひとつのつもりです！

**Comment by yoshitsugu** [comment]
@eatplaynap なるほど。一日1レコードの制約をきっちりDBで表現できるように、 `practice_on` みたいな `date` 型のカラムを作って、 `user_id` と `practice_on` でユニークインデックスをはってもいいかもなと思いました。
ユニークインデックスがあればうっかり1日複数レコード作られてしまうことがDB上で防げると思います。
https://yamakichi.hatenablog.com/entry/2016/08/25/003738
この `もう一つ、一意制約の状態を担保する手段としてDB側にunique indexを追加する方法があります。` 以下のイメージです。

**Comment by eatplaynap** [comment]
@yoshitsugu 
レビューありがとうございます！参考URL拝読し、ユニークインデックスの必要性が理解できました。
2点質問があるのですが、
1. `practice_on`と`created_at`は同じ日時になるイメージなのですが、`created_at`の他に`practice_on`も別途必要なのでしょうか？
1. Practiceモデルのマイグレーションファイルは下記のようなイメージです。ER図で`practice_on`と`user_id`とのユニークインデックスを表現したい場合はどう書けばよいのでしょうか？
```ruby
class CreatePractice < ActiveRecord::Migration
  def change
    create_table :practices do |t|
      t.references :user, foreign_key: true
      t.integer :practice_id, null: false
      t.string :url, null: false
      t.integer :minutes, null: false
      t.text :memo
      t.date :practice_on
      t.timestamp
    end
    add_index :practices, [:user_id, :practice_on], unique: true
  end
end
```

**Comment by yoshitsugu** [comment]
@eatplaynap 

1. いい質問ですね。厳密にいうと `created_at` は時刻も含めた時間表示になりますが、 `practice_on` は日付のみになるかと思いますので、そこがちょっと違います。

- 日付での縛りをいれたいので、日付のカラムでユニークインデックスをはれるようにしたほうがよさそう。
- `created_at` は `practice_on` とはレコードが作成された日時」と「記録対象の日付」で意味が違います。なので、たとえば3日分をあとで記録する、などもこれらをわけておくことで対応ができます(今回はそこまでいらないとは思いますが)

という理由でわけたほうがいいかなと思っていました。

2. たぶんER図では表現できないと思う(僕が知らないだけかもしれないですが)ので、文章で補うなどしてもらえば十分かなと思います〜

**Comment by eatplaynap** [comment]
@yoshitsugu 
> 日付での縛りをいれたい
> たとえば3日分をあとで記録する、などもこれらをわけておくことで対応ができます

なるほど！納得しました。確かに`created_at`だけだと後からのデータ追加には対応できないですね。

レビュー結果を反映させてER図を修正しましたのでご確認お願いいたします。
あと質問漏れてしまったのですが、学習時間を表すカラム名`minutes`は複数形でも不自然ではないでしょうか？

**Comment by yoshitsugu** [comment]
いいと思います :+1: 

> あと質問漏れてしまったのですが、学習時間を表すカラム名minutesは複数形でも不自然ではないでしょうか？

問題ないと思います〜

**Comment by eatplaynap** [comment]
close the issue as it got approval from yoshitsugu-san
